# Generated by Django 5.0.2 on 2024-02-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberofusers', models.IntegerField()),
                ('group', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Group',
            },
        ),
    ]
