# Generated by Django 5.0.2 on 2024-02-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
