# Generated by Django 5.0.2 on 2024-02-23 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_app', '0002_alter_group_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensesTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.CharField(max_length=20)),
                ('whopaid', models.CharField(max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share_app.group')),
            ],
            options={
                'db_table': 'ExpensesTracker',
            },
        ),
    ]
