# Generated by Django 5.0.2 on 2024-02-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_app', '0003_expensestracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensestracker',
            name='expenseAmount',
            field=models.IntegerField(default=0),
        ),
    ]
