# Generated by Django 5.0.2 on 2024-02-25 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_app', '0004_expensestracker_expenseamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensestracker',
            name='howtosplit',
            field=models.CharField(choices=[('eq', 'Equal'), ('Ex', 'Exact'), ('Sp', 'Split')], default='Select from below options', max_length=2),
        ),
        migrations.CreateModel(
            name='expesneForGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share_app.group')),
            ],
        ),
    ]
