# Generated by Django 5.0.2 on 2024-02-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_app', '0007_expensestracker_providesplit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensestracker',
            name='howtosplit',
            field=models.CharField(choices=[('eq', 'Equal'), ('Ex', 'Exact'), ('%', 'Percetage')], default='Select from below options', max_length=2, verbose_name='How to split?'),
        ),
    ]
